### ISSUE TITLE
Converting a json import that doesn't work as expected

### ISSUE THREAD

**Issue by Innei** [ts-bridge/ts-bridge#22]
## Description

ts-bridge converts json imports to .json.cjs or .json.mjs after compilation, which is incorrect behavior.

![CleanShot 2024-06-29 at 2  01 37@2x](https://github.com/ts-bridge/ts-bridge/assets/41265413/44cbe7fd-5dd4-4a14-953a-0dd602fa4230)

```
require("./data.json.cjs") // should be require("./data.json")
```

## Steps to reproduce

https://github.com/Innei/ts-bridge-repro

Refer: https://github.com/MetaMask/providers/issues/339

**Comment by Mrtenz** [comment]
This is fixed in `@ts-bridge/cli@0.2.0`. Thanks for reporting it!
