### ISSUE TITLE
ts-bridge build does not compile properly with React Native in a monorepo

### ISSUE THREAD

**Issue by brianacnguyen** [ts-bridge/ts-bridge#72]
## Description
The `ts-bridge` build is currently experiencing issues with React Native in a monorepo setup (not yet tested in a standalone repository). The screenshots below illustrate the build behavior when using tsc
<img width="708" alt="Screenshot 2024-12-10 at 8 07 50 AM" src="https://github.com/user-attachments/assets/a1e40e91-655e-4b98-a002-bda0f1ed3067">
<img width="1043" alt="Screenshot 2024-12-10 at 8 06 56 AM" src="https://github.com/user-attachments/assets/b0b6909d-de34-473b-a1ea-c62cd46f24b2">

Compared to when using `ts-bridge`
<img width="693" alt="Screenshot 2024-12-10 at 8 08 08 AM" src="https://github.com/user-attachments/assets/5787302b-4960-414b-8d72-bc281f5e7ed4">
<img width="1372" alt="Screenshot 2024-12-10 at 8 03 21 AM" src="https://github.com/user-attachments/assets/3415b2d1-2a2a-4d46-8bce-178f2d6c1c83">
<img width="1507" alt="Screenshot 2024-12-10 at 8 07 20 AM" src="https://github.com/user-attachments/assets/2910c013-2d0d-4a5a-bb8f-8b47228b44c4">

## Steps to reproduce

1. Clone https://github.com/MetaMask/metamask-design-system
2. Change the build script for the package `design-system-react-native` and/or `design-system-twrnc-preset` to use `ts-bridge`
3. Run `yarn workspace @metamask/design-system-react-native build` or `yarn workspace @metamask/design-system-twrnc-preset build` from root or `yarn build` in the respective package
4. Observe error

**Comment by Mrtenz** [comment]
This is an annoying one. `react-native` doesn't specify a `main` or `exports` field, but it has a `index.js`, so Node.js (thus `ts-bridge`) falls back to that, but the `index.js` is actually Flow, not plain JavaScript. `ts-bridge` tries to rewrite imports if they are not detected by `cjs-module-lexer`, which does not work for Flow. We may just need to assume the best case scenario when a package cannot be parsed, and leave imports as-is.
